# ─────────────────────────────────────────────────────────────────────────────
#  Titan API — Makefile
#  Creator: Antmind Ventures Private Limited
#  Production server: titan.antmind.ai  (72.61.177.156 · Ubuntu 24.04)
# ─────────────────────────────────────────────────────────────────────────────

COMPOSE       := docker compose
COMPOSE_DEV   := $(COMPOSE) --profile dev
COMPOSE_PROD  := $(COMPOSE) --profile prod
COMPOSE_ALL   := $(COMPOSE) --profile dev --profile prod
DOMAIN   := titan.antmind.ai
EMAIL    := admin@antmind.ai

.DEFAULT_GOAL := help

# ── Help ─────────────────────────────────────────────────────────────────────
.PHONY: help
help:
	@echo ""
	@echo "  ████████╗██╗████████╗ █████╗ ███╗   ██╗"
	@echo "     ██╔══╝██║╚══██╔══╝██╔══██╗████╗  ██║"
	@echo "     ██║   ██║   ██║   ███████║██╔██╗ ██║"
	@echo "     ██║   ██║   ██║   ██╔══██║██║╚██╗██║"
	@echo "     ██║   ██║   ██║   ██║  ██║██║ ╚████║"
	@echo "     ╚═╝   ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═══╝"
	@echo "  Antmind Ventures Private Limited"
	@echo ""
	@echo "  ── First time ─────────────────────────────────────────────────────"
	@echo "  make setup           Build, run migrations, start prod profile"
	@echo "  make setup-dev       Build, run migrations, start dev profile (no nginx/ssl)"
	@echo "  make ssl             Obtain SSL certificate from Let's Encrypt"
	@echo ""
	@echo "  ── Daily operations ───────────────────────────────────────────────"
	@echo "  make up              Start prod profile services"
	@echo "  make up-dev          Start dev profile services"
	@echo "  make down            Stop all services"
	@echo "  make down-dev        Stop dev profile services"
	@echo "  make restart         Restart all services"
	@echo "  make restart-dev     Restart dev profile services"
	@echo "  make deploy          Pull, rebuild, migrate, restart (zero-downtime)"
	@echo "  make status          Show container status"
	@echo "  make status-dev      Show dev profile container status"
	@echo ""
	@echo "  ── Database / Migrations ───────────────────────────────────────────"
	@echo "  make migrate                Apply pending migrations"
	@echo "  make migration name=<name>  Create autogenerated migration"
	@echo "  make downgrade              Roll back one migration"
	@echo "  make migration-history      Show migration log"
	@echo ""
	@echo "  ── Logs ───────────────────────────────────────────────────────────"
	@echo "  make logs            All services"
	@echo "  make logs-dev        Dev profile services"
	@echo "  make logs-app        App only"
	@echo "  make logs-worker     ARQ worker only"
	@echo "  make logs-nginx      Nginx only"
	@echo ""
	@echo "  ── Shells ─────────────────────────────────────────────────────────"
	@echo "  make shell           Bash in app container"
	@echo "  make shell-worker    Bash in ARQ worker container"
	@echo "  make shell-db        psql in postgres container"
	@echo "  make shell-redis     redis-cli in redis container"
	@echo ""
	@echo "  ── Linting ─────────────────────────────────────────────────────────"
	@echo "  make lint            Check code  (ruff lint + format)"
	@echo "  make lint-fix        Auto-fix all fixable issues"
	@echo "  make install-hooks   Install git pre-commit hooks (run once)"
	@echo ""
	@echo "  ── Maintenance ────────────────────────────────────────────────────"
	@echo "  make build           Rebuild Docker images"
	@echo "  make build-no-cache  Rebuild without layer cache"
	@echo "  make clean           Remove containers + volumes  ⚠ DELETES DATA"
	@echo ""

# ── First-time setup ─────────────────────────────────────────────────────────
.PHONY: setup
setup:
	@echo "==> Titan first-time setup..."
	@[ -f .env ] || (echo "ERROR: .env not found — copy .env.example and fill values" && exit 1)
	@$(COMPOSE_PROD) build
	@$(COMPOSE_PROD) up -d postgres redis
	@echo "    Waiting for Postgres to be healthy..."
	@$(COMPOSE_PROD) run --rm -e RUN_MIGRATIONS=true app alembic upgrade head
	@$(COMPOSE_PROD) up -d
	@echo ""
	@echo "  ✓  Titan is live!  Run 'make ssl' next to enable HTTPS."
	@echo "     Swagger: http://$(DOMAIN)/docs"
	@echo "     Health:  http://$(DOMAIN)/api/v1/health"
	@echo ""

.PHONY: setup-dev
setup-dev:
	@echo "==> Titan dev setup (no nginx/ssl)..."
	@[ -f .env ] || (echo "ERROR: .env not found — copy .env.example and fill values" && exit 1)
	@$(COMPOSE_DEV) build
	@$(COMPOSE_DEV) up -d postgres redis
	@echo "    Waiting for Postgres to be healthy..."
	@$(COMPOSE_DEV) run --rm -e RUN_MIGRATIONS=true app alembic upgrade head
	@$(COMPOSE_DEV) up -d
	@echo ""
	@echo "  ✓  Titan dev profile is live (nginx/certbot not started)."
	@echo ""

# ── Start / Stop / Deploy ────────────────────────────────────────────────────
.PHONY: up
up:
	@$(COMPOSE_PROD) up -d

.PHONY: up-dev
up-dev:
	@$(COMPOSE_DEV) up -d

.PHONY: down
down:
	@$(COMPOSE_ALL) down

.PHONY: down-dev
down-dev:
	@$(COMPOSE_DEV) down

.PHONY: restart
restart:
	@$(COMPOSE_PROD) restart

.PHONY: restart-dev
restart-dev:
	@$(COMPOSE_DEV) restart

.PHONY: build
build:
	@$(COMPOSE_PROD) build

.PHONY: build-no-cache
build-no-cache:
	@$(COMPOSE_PROD) build --no-cache

.PHONY: deploy
deploy:
	@echo "==> Deploying Titan..."
	@git pull --ff-only
	@$(COMPOSE_PROD) build
	@$(COMPOSE_PROD) run --rm -e RUN_MIGRATIONS=true app alembic upgrade head
	@$(COMPOSE_PROD) up -d --remove-orphans
	@echo "==> Deploy complete — $(DOMAIN)"

# ── Migrations ────────────────────────────────────────────────────────────────
.PHONY: migrate
migrate:
	@echo "==> Applying migrations..."
	@$(COMPOSE_PROD) exec app alembic upgrade head
	@echo "==> Done"

.PHONY: migration
migration:
	@[ -n "$(name)" ] || (echo "Usage: make migration name=<description>" && exit 1)
	@$(COMPOSE_PROD) exec app alembic revision --autogenerate -m "$(name)"

.PHONY: downgrade
downgrade:
	@$(COMPOSE_PROD) exec app alembic downgrade -1

.PHONY: migration-history
migration-history:
	@$(COMPOSE_PROD) exec app alembic history --verbose

# ── Logs ─────────────────────────────────────────────────────────────────────
.PHONY: logs logs-dev logs-app logs-worker logs-nginx
logs:
	@$(COMPOSE_PROD) logs -f

logs-dev:
	@$(COMPOSE_DEV) logs -f

logs-app:
	@$(COMPOSE_PROD) logs -f app

logs-worker:
	@$(COMPOSE_PROD) logs -f arq-worker

logs-nginx:
	@$(COMPOSE_PROD) logs -f nginx

# ── Status ────────────────────────────────────────────────────────────────────
.PHONY: status ps
status ps:
	@$(COMPOSE_ALL) ps

.PHONY: status-dev
status-dev:
	@$(COMPOSE_DEV) ps

# ── Shells ────────────────────────────────────────────────────────────────────
.PHONY: shell shell-worker shell-db shell-redis
shell:
	@$(COMPOSE_PROD) exec app bash

shell-worker:
	@$(COMPOSE_PROD) exec arq-worker bash

shell-db:
	@$(COMPOSE_PROD) exec postgres psql -U $${DB_USER:-titan} -d $${DB_NAME:-titan}

shell-redis:
	@$(COMPOSE_PROD) exec redis redis-cli

# ── SSL (Let's Encrypt) ───────────────────────────────────────────────────────
.PHONY: ssl
ssl:
	@echo "==> Switching Nginx to HTTP challenge mode..."
	@if grep -q '^NGINX_CONF=' .env; then \
		sed -i.bak 's/^NGINX_CONF=.*/NGINX_CONF=titan.conf/' .env; \
	else \
		echo 'NGINX_CONF=titan.conf' >> .env; \
	fi
	@rm -f .env.bak
	@$(COMPOSE_PROD) up -d nginx
	@echo "==> Obtaining SSL certificate for $(DOMAIN)..."
	@$(COMPOSE_PROD) run --rm --entrypoint certbot certbot certonly \
		--webroot \
		--webroot-path=/var/www/certbot \
		--email $(EMAIL) \
		--agree-tos \
		--no-eff-email \
		--keep-until-expiring \
		-d $(DOMAIN)
	@echo "==> Enabling production TLS config..."
	@if grep -q '^NGINX_CONF=' .env; then \
		sed -i.bak 's/^NGINX_CONF=.*/NGINX_CONF=titan-prod.conf/' .env; \
	else \
		echo 'NGINX_CONF=titan-prod.conf' >> .env; \
	fi
	@rm -f .env.bak
	@$(COMPOSE_PROD) up -d nginx
	@$(COMPOSE_PROD) exec -T nginx nginx -t
	@echo "==> HTTPS enabled — $(DOMAIN)"

# ── Linting ───────────────────────────────────────────────────────────────────
.PHONY: install-hooks
install-hooks:
	@command -v pre-commit > /dev/null 2>&1 || pip install pre-commit
	@pre-commit install
	@echo "==> Git pre-commit hooks installed. Ruff will run on every commit."

.PHONY: lint
lint:
	@command -v pre-commit > /dev/null 2>&1 || (echo "Run 'make install-hooks' first." && exit 1)
	@pre-commit run --all-files

.PHONY: lint-fix
lint-fix:
	@command -v ruff > /dev/null 2>&1 || pip install ruff
	@ruff check --fix app/ alembic/ gunicorn.conf.py
	@ruff format app/ alembic/ gunicorn.conf.py
	@echo "==> All fixes applied."

# ── Destructive ───────────────────────────────────────────────────────────────
.PHONY: clean
clean:
	@echo "WARNING: removes ALL containers and volumes — all data will be lost."
	@read -p "Type 'yes' to confirm: " c && [ "$$c" = "yes" ] || (echo "Aborted." && exit 1)
	@$(COMPOSE_ALL) down -v --remove-orphans
	@echo "==> Cleaned."
